#   Copyright 2023 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.3
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
version: '3.7'
services:
  ita-ag-ansible-execution:
    image: docker.io/exastro/exastro-it-automation-ag-ansible-execution:${ITA_VERSION:-2.5.0}
    container_name: ${ANSIBLE_AGENT_NAME:-agent-ansible-execution-01}
    hostname: ${ANSIBLE_AGENT_NAME:-agent-ansible-execution-01}
    restart: always
    user: ${UID:-1000}:${HOST_DOCKER_GID:-1000}
    environment:
      TZ: ${TZ:-Asia/Tokyo}
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-ja}
      LANGUAGE: ${LANGUAGE:-en}
      ANSIBLE_AGENT_NAME: ${ANSIBLE_AGENT_NAME:-agent-ansible-execution-01}
      ANSIBLE_EXASTRO_ORGANIZATION_ID: ${ANSIBLE_EXASTRO_ORGANIZATION_ID}
      ANSIBLE_EXASTRO_WORKSPACE_ID: ${ANSIBLE_EXASTRO_WORKSPACE_ID}
      ANSIBLE_EXASTRO_REFRESH_TOKEN: ${ANSIBLE_EXASTRO_PASSWORD}
      ANSIBLE_EXASTRO_URL: ${ANSIBLE_EXASTRO_URL}
      ANSIBLE_ITERATION: ${ANSIBLE_ITERATION:-10}
      ANSIBLE_EXECUTE_INTERVAL: ${ANSIBLE_EXECUTE_INTERVAL:-3}
      ANSIBLE_LOG_LEVEL: ${ANSIBLE_LOG_LEVEL:-INFO}
      ANSIBLE_CHILD_PROCESS_RETRY_LIMIT: ${ANSIBLE_CHILD_PROCESS_RETRY_LIMIT:-0}
    volumes:
      - vol-ita-storage:/storage
    networks:
      - exastro
    logging:
      driver: json-file
      options:
        max-size: ${LOGGING_MAX_SIZE:-10m}
        max-file: '${LOGGING_MAX_FILE:-10}'

volumes:
  vol-ita-storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/.volumes/storage

networks:
  exastro:
    name: "exastro_${NETWORK_ID}"
