version: '3.7'
services:
  ita_ansible_agent:
    labels:
      - organization_id={{ organization_id }}
      - workspace_id={{ workspace_id }}
      - execution_no={{ execution_no }}
    image: "{{ ansible_agent_image }}"
    build:
      context: ./work/
      args:
        ANSIBLE_AGENT_IMAGE: "${ANSIBLE_AGENT_IMAGE}"
        ANSIBLE_AGENT_IMAGE_TAG: "${ANSIBLE_AGENT_IMAGE_TAG}"
        ANSIBLE_AGENT_BASE_IMAGE: "${ANSIBLE_AGENT_BASE_IMAGE}"
        ANSIBLE_AGENT_BASE_IMAGE_TAG: "${ANSIBLE_AGENT_BASE_IMAGE_TAG}"
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        PYTHONPATH: "/usr/local/lib/python3.9/site-packages:/home/app_user/.local/lib/python3.9/site-packages:$PYTHONPATH"
    user: ${UID:-1000}:${HOST_DOCKER_GID:-1000}
    entrypoint:
      - "bash"
      - "-c"
      - "{{ str_shell_command }}"
    volumes:
      - type: bind
        source: {{ host_mount_path_driver }}
        target: {{ container_mount_path_driver }}
      - type: bind
        source: {{ host_mount_path_conductor }}
        target: {{ container_mount_path_conductor }}
    environment:
      EXEC_DIR: {{ container_mount_path_driver }}
      PYTHONPATH: "/usr/local/lib/python3.9/site-packages:/home/app_user/.local/lib/python3.9/site-packages:$PYTHONPATH"
    networks:
      - exastro

networks:
  exastro:
    name: exastro_{{ network_id }}
    external: true
